version: '3'

services:

  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/provision/authentication-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/provision/broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  frontend:
    build:
      context: ./../micro-frontend
      dockerfile: provision/micro-frontend.dockerfile
    restart: always
    ports:
      - "8000:80"
