version: '3'

services:

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/provision/broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  frontend:
    build:
      context: ./../micro-frontend
      dockerfile: provision/micro-frontend.dockerfile
    restart: always
    ports:
      - "8000:80"
